package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	Document      struct {
		DocumentNo     string `json:"document_no"`
		DeliverTo      string `json:"deliver_to"`
		Quantity       string `json:"quantity"`
		PickedQuantity string `json:"picked_quantity"`
		Price          string `json:"price"`
		Batch          string `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema      string `json:"api_schema"`
	MaterialCode   string `json:"material_code"`
	Plant_Supplier string `json:"plant/supplier"`
	Stock          string `json:"stock"`
	DocumentType   string `json:"document_type"`
	DocumentNo     string `json:"document_no"`
	PlannedDate    string `json:"planned_date"`
	ValidatedDate  string `json:"validated_date"`
	Deleted        bool   `json:"deleted"`
}

type SDC struct {
	ConnectionKey       string `json:"connection_key"`
	Result              bool   `json:"result"`
	RedisKey            string `json:"redis_key"`
	Filepath            string `json:"filepath"`
	MaintenanceTaskList struct {
		TaskListType                string      `json:"TaskListType"`
		TaskListGroup               string      `json:"TaskListGroup"`
		TaskListGroupCounter        string      `json:"TaskListGroupCounter"`
		TaskListVersionCounter      string      `json:"TaskListVersionCounter"`
		MaintenancePlanningPlant    string      `json:"MaintenancePlanningPlant"`
		TaskListStatus              string      `json:"TaskListStatus"`
		TaskListStatusDesc          string      `json:"TaskListStatusDesc"`
		TechnicalObject             string      `json:"TechnicalObject"`
		TaskListUsage               string      `json:"TaskListUsage"`
		TaskListDesc                string      `json:"TaskListDesc"`
		WorkCenter                  string      `json:"WorkCenter"`
		MaintenanceStrategy         string      `json:"MaintenanceStrategy"`
		OperationSystemCondition    string      `json:"OperationSystemCondition"`
		Assembly                    string      `json:"Assembly"`
		ChangeNumber                string      `json:"ChangeNumber"`
		ValidityStartDate           string      `json:"ValidityStartDate"`
		ValidityEndDate             string      `json:"ValidityEndDate"`
		IsMarkedForDeletion         bool        `json:"IsMarkedForDeletion"`
		LastChangeDate              string      `json:"LastChangeDate"`
		CreationDate                string      `json:"CreationDate"`
		Plant                       string      `json:"Plant"`
		ResponsiblePlannerGroup     string      `json:"ResponsiblePlannerGroup"`
		Equipment                   string      `json:"Equipment"`
		FunctionalLocationLabelName string      `json:"FunctionalLocationLabelName"`
		TaskListIsHierarchical      bool        `json:"TaskListIsHierarchical"`
		StrategyPackage             struct {
			TaskListType                   string `json:"TaskListType"`
			TaskListGroup                  string `json:"TaskListGroup"`
			TaskListGroupCounter           string `json:"TaskListGroupCounter"`
			TaskListSequence               string `json:"TaskListSequence"`
			TaskListOperationInternalID    string `json:"TaskListOperationInternalID"`
			MaintenancePackage             string `json:"MaintenancePackage"`
			MaintPckgTskListOpAllocIntNmbr string `json:"MaintPckgTskListOpAllocIntNmbr"`
			MaintenancePackageText         string `json:"MaintenancePackageText"`
			MaintenanceTaskListOperation   string `json:"MaintenanceTaskListOperation"`
			OperationText                  string `json:"OperationText"`
			MaintTaskListSubOperation      string `json:"MaintTaskListSubOperation"`
			ChangeNumber                   string `json:"ChangeNumber"`
			Operation                      struct {
				TaskListType                   string      `json:"TaskListType"`
				TaskListOpBOMItmIntVersCounter string      `json:"TaskListOpBOMItmIntVersCounter"`
				MaintenanceTaskListOperation   string      `json:"MaintenanceTaskListOperation"`
				MaintOperationExecStageCode    string      `json:"MaintOperationExecStageCode"`
				OperationText                  string      `json:"OperationText"`
				OperationControlProfile        string      `json:"OperationControlProfile"`
				WorkCenter                     string      `json:"WorkCenter"`
				Plant                          string      `json:"Plant"`
				Assembly                       string      `json:"Assembly"`
				OperationCalculationControl    string      `json:"OperationCalculationControl"`
				OpPlannedWorkQuantity          float64     `json:"OpPlannedWorkQuantity"`
				OpWorkQuantityUnit             string      `json:"OpWorkQuantityUnit"`
				NumberOfCapacities             int         `json:"NumberOfCapacities"`
				PurchaseOrderQty               float64     `json:"PurchaseOrderQty"`
				PurchaseOrderQuantityUnit      string      `json:"PurchaseOrderQuantityUnit"`
				OperationStandardDuration      float64     `json:"OperationStandardDuration"`
				OperationStandardDurationUnit  string      `json:"OperationStandardDurationUnit"`
				CostCtrActivityType            string      `json:"CostCtrActivityType"`
				MaterialGroup                  string      `json:"MaterialGroup"`
				OpExternalProcessingPrice      float64     `json:"OpExternalProcessingPrice"`
				OpExternalProcessingCurrency   string      `json:"OpExternalProcessingCurrency"`
				CostElement                    string      `json:"CostElement"`
				PurchasingGroup                string      `json:"PurchasingGroup"`
				PurchasingOrganization         string      `json:"PurchasingOrganization"`
				PurchaseContract               string      `json:"PurchaseContract"`
				PurchaseContractItem           string      `json:"PurchaseContractItem"`
				Supplier                       string      `json:"Supplier"`
				ChangeNumber                   string      `json:"ChangeNumber"`
				PurchasingInfoRecord           string      `json:"PurchasingInfoRecord"`
				IsBusinessPurposeCompleted     string      `json:"IsBusinessPurposeCompleted"`
				SupplierAccountGroup           string      `json:"SupplierAccountGroup"`
				TaskListStatus                 string      `json:"TaskListStatus"`
				ResponsiblePlannerGroup        string      `json:"ResponsiblePlannerGroup"`
				MaintenancePlanningPlant       string      `json:"MaintenancePlanningPlant"`
				MaintenancePlannerGroup        string      `json:"MaintenancePlannerGroup"`
				ControllingArea                string      `json:"ControllingArea"`
				CostCenter                     string      `json:"CostCenter"`
				MaintenancePlant               string      `json:"MaintenancePlant"`
				ValidityStartDate              string      `json:"ValidityStartDate"`
				ValidityEndDate                string      `json:"ValidityEndDate"`
				TechnicalObject                string      `json:"TechnicalObject"`
				TechObjIsEquipOrFuncnlLoc      string      `json:"TechObjIsEquipOrFuncnlLoc"`
				OperationMaterial              struct {
					TaskListType                   string      `json:"TaskListType"`
					TaskListGroup                  string      `json:"TaskListGroup"`
					TaskListGroupCounter           string      `json:"TaskListGroupCounter"`
					TaskListSequence               string      `json:"TaskListSequence"`
					TaskListOperationInternalID    string      `json:"TaskListOperationInternalID"`
					TaskListOpBOMItmInternalID     string      `json:"TaskListOpBOMItmInternalID"`
					TaskListOpBOMItmIntVersCounter string      `json:"TaskListOpBOMItmIntVersCounter"`
					MaintenanceTaskListOperation   string      `json:"MaintenanceTaskListOperation"`
					Material                       string      `json:"Material"`
					MaterialName                   string      `json:"MaterialName"`
					BillOfMaterialItemQuantity     int         `json:"BillOfMaterialItemQuantity"`
					BillOfMaterialItemCategory     string      `json:"BillOfMaterialItemCategory"`
					BillOfMaterialItemUnit         string      `json:"BillOfMaterialItemUnit"`
					ResvnIsMRPRlvtOrPurReqnIsCrted string      `json:"ResvnIsMRPRlvtOrPurReqnIsCrted"`
					MatlCompIsMarkedForBackflush   bool        `json:"MatlCompIsMarkedForBackflush"`
					SafetyRelevantObject           string      `json:"SafetyRelevantObject"`
					BillOfMaterialItemCategoryDesc string      `json:"BillOfMaterialItemCategoryDesc"`
					MatlsPlngRelevancyCodeName     string      `json:"MatlsPlngRelevancyCodeName"`
					SafetyRelevanceActionDesc      string      `json:"SafetyRelevanceActionDesc"`
				} `json:"OperationMaterial"`
			} `json:"Operation"`
		} `json:"StrategyPackage"`
	} `json:"MaintenanceTaskList"`
	APISchema             string   `json:"api_schema"`
	Accepter              []string `json:"accepter"`
	MaintenanceTaskListNo string   `json:"maintenance_task_list"`
	Deleted               bool     `json:"deleted"`
}
